apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: 293861751646.dkr.ecr.us-east-2.amazonaws.com/demo-frontend
  newName: 293861751646.dkr.ecr.us-east-2.amazonaws.com/demo-frontend
  newTag: f0f0f118
resources:
- ../../base
patchesStrategicMerge:
- front-deployment-patch.yaml
- front-service-patch.yaml
